### ISSUE TITLE
OUTPUT: units - need to have output in cm not in pixels and meters.

### ISSUE THREAD

**Issue by JennR1990** [thartbm/PySelector#11]

**Comment by thartbm** [comment]
Did you set it correctly in the settings?

**Comment by thartbm** [comment]
Actually, while the exact unit is somewhat irrelevant, it has to be the same unit for all sets of coordinates, both within the PySelector and in the output. That is: robot, tablet, touchscreen and stimulus coordinates should be in the same unit, and with 0,0 at the home position. Using centimeters makes sense for analyses on the output and should be possible given the correct settings.
