### ISSUE TITLE
Settings menu needs to be changed

### ISSUE THREAD

**Issue by thartbm** [thartbm/PySelector#15]
There should be 3 options:

1) settings folder
2) quick settings >
3) interactive settings...

Option 1 should show a little pop-up to allow people to set the folder where the settings are (or even create a new folder?). That is: change the 'Location' value in the main settings.json.

Option 2 should show the list of settings in the current Location folder and load them when someone selects one. Perhaps this should show that the currently selected folder is empty (and to go to the interactive option to create settings) or that the folder doesn't exist, so to go to the previous option to select an existing folder.

Option 3 should open the create / load / edit window. Maybe it should be called 'interactive...' ? Right now it's a bit mysterious where to go to change, create, load whatever a settings file in such a way that we can see what the settings are. And the main folder ('Location' value) should be editable by pointing & clicking, so there should be an option for that too in the menu.

**Comment by ATajadod94** [comment]
Added the new option. We'll wait to make sure it works on Jen's and other computers before closing
