### ISSUE TITLE
trial jump button 

### ISSUE THREAD

**Issue by ayalamar** [thartbm/PySelector#16]

**Comment by ATajadod94** [comment]
Not closing this as we need to decide on 
1) where and how to display the goto button (assuming we want it changed)
2) Whether the user can use the go button to jump trials even if they have not accepted the previous trial

**Comment by thartbm** [comment]
Core functionality. Make it work like in the Matlab version:

- If people put an integer number in the GO button field, the GUI should go to that trial, provided it exists in the data, if it does not exist, give a warning.
- If people do not put anything in the GO button field, go to the next non-selected trial.

This should be close to (integrated in) the other navigational buttons (accept/reject/next/...)

FYI: you didn't close the issue, it's still in the list of open issues.
