### ISSUE TITLE
Make settings folder OS-independent

### ISSUE THREAD

**Issue by thartbm** [thartbm/PySelector#21]
The settings folder needs to be specified in a platform independent way.

For joining paths,` os.path.join()` is very useful, as it knows the current operating systems path seperator ('/' for linux and mac and '\\' for windows). I imagine that `os.path.sep()` might also be helpful.

**Comment by ATajadod94** [comment]
The setting folder is returned by the wxpython module when the user selects it in the folder dialog. Therefore, it will always be system dependent as is.

I changed the default folder to be system independent.
