### ISSUE TITLE
Overwrite any headers in data with headers in settings if there is a duplicate issue

### ISSUE THREAD

**Issue by JennR1990** [thartbm/PySelector#26]

**Comment by thartbm** [comment]
Core functionality, but new. Make it work, here's how it should work:

0: Test if there is a header in the file.
1: Check if there is a header line in the settings.

Now there are three/four situations possible:
a) If only one is there, use that one.
b) If there is none, give a warning.
c) If there are two, use the header from the settings (this way the header line in the data can be overruled in a consistent way).
