### ISSUE TITLE
Crashes trying to move to next trial after changing p1 and p2

### ISSUE THREAD

**Issue by JennR1990** [thartbm/PySelector#31]
I was selecting a reach file and finished that so i opened a no-cursor file and it would not move to the next trial.  
StopIteration
Traceback (most recent call last):
  File "C:\Users\jeruttle\Documents\Jenn\PySelect\gui\mainwindow.py", line 316, in nexttrial
    self.parent.updateoutput()
  File "C:\Users\jeruttle\Documents\Jenn\PySelect\gui\mainwindow.py", line 205, in updateoutput
    maxvel_idx = next(x[0] for x in enumerate(self.trial_data.time_ms) if x[1] >= self.trial_data.selectedmaxvelocity)
StopIteration

Also tried a No-cursor file first and then a reach file, i was able to continue selecting (perhaps i was not pressing accept before).  I was able to select a couple of the reach trials but once i changed p1 and p2 it gave me a bunch of problems moving forward.  I was able to go previous then when i went forward the changes i made to p1 and p2 were reset back to default.  So i tried changing p1 and p2 on another trial and then clicked accept and it wouldnt move forward and gave me the same error as above. 

This does not appear to be happening anymore. Do not focus on right now.

**Comment by thartbm** [comment]
Seems like core functionality. Please make this work.

**Comment by ATajadod94** [comment]
unable to recreate issue and based on "This does not appear to be happening anymore. Do not focus on right now" , I am closing this issue
