### ISSUE TITLE
Headers: allow "hand", "robot" and "pen" coordinates (with units)

### ISSUE THREAD

**Issue by thartbm** [thartbm/PySelector#42]
The GUI should be able to read data files that encode the hand position using 'pen' columns, using 'robot' columns and using 'hand' columns.

These should be renamed to 'hand' columns internally, and they should be converted to centimeters before selection.

The 'cursor' data should always be called 'cursor' in the raw data, and remain 'cursor in the output. But it should be converted to centimeters using the settings.

The output for robot, pen and hand positions should always be called 'hand' in the output (so all our scripts work). And the units should be centimeter for ALL position columns, hand, cursor, target, ... and the origin (0,0) should be at the home position (if there is only one, not sure how to hand two or more yet).

**Comment by ATajadod94** [comment]
`
            if key.startswith(('penx', 'robotx', 'mousex', 'handx')):
`

added the above line for x and y values for the input where key is the specified header in the setting files. In all instance, the key value is changed to handx,handy and the previous key is dropped from the data

`
                   data['handy_cm'] = data[key].astype('float') ## followed by appropriate calculation  
                    data.drop(key, axis=1, inplace=True)
`
